version: "3"
name: homeassistant_stack
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - ./homeassistant/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - ./portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: unless-stopped
