version: "3"
name: homeassistant_stack
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - ./localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    restart: unless-stopped
