version: "3"
name: grafana_stack
services:
  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - ./portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: unless-stopped
