version: "3"
name: grafana_stack
services:
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    restart: unless-stopped
