version: "3"
name: full_stack
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - ./localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    restart: unless-stopped
